### ISSUE TITLE
Remove Vagrantfile and Vagrant guide from readme

### ISSUE THREAD

**Issue by lukehinds** [keylime/ansible-keylime#14]
This role is for deploying Keylime with a HW TPM. We should remove all the references to Vargant.

**Comment by dawud** [comment]
I have kept those files and references in #17, but can drop them as well.
However, it might be useful for development/testing activities (not production) when coupled with a software TPM?

Another idea, the role could check for the target machine to be physical and warn or fail otherwise.

**Comment by lukehinds** [comment]
> I have kept those files and references in #17, but can drop them as well.
> However, it might be useful for development/testing activities (not production) when coupled with a software TPM?
> 
> Another idea, the role could check for the target machine to be physical and warn or fail otherwise.

So we have a sandbox / development ansible role here:

https://github.com/keylime/ansible-keylime-tpm-emulator

The idea is that the two roles keep a clear separation , to prevent folks using Keylime in a production environment. For example in the ansible emulator role, we set `require_ek` to false. A software TPM emulator has no entity key (unlike a hardware TPM). 

https://github.com/keylime/ansible-keylime-tpm-emulator/blob/2b87f1bf20037b75e80ce7aabd8662432ad702a7/roles/ansible-keylime-tpm20/tasks/keylime.yml#L13-L17

If you ran Keylime with the `require_ek` the boolean set to `False` with a hardware TPM, you won't have a hardware route of trust, as Keylime won't check the EK (entity key' has been signed by a manufacturer:

 We gather the certs here:

https://github.com/keylime/keylime/blob/5f92021e64e6a08d5cf2f14b1f2e60293ddf60b8/keylime/tpm_ek_ca.py#L49-L55

and we validate the signing authority here:

https://github.com/keylime/keylime/blob/5f92021e64e6a08d5cf2f14b1f2e60293ddf60b8/keylime/tpm2.py#L853-L863

Anyway, I digress a bit there. In regards to having two roles, I am not of that strong opinion here. If someone was to refactor into a single role and make it loud and clear about only using the soft tpm path, for non production use, I certainly would not be opposed. However its not causing us too much pain maintaining them both.

**Comment by dawud** [comment]
Removal of Vagrant related content will be included in #17
