### ISSUE TITLE
Alembic dependency not installed

### ISSUE THREAD

**Issue by RUKip** [keylime/ansible-keylime#19]
Alembic is not installed during setup. Resulting in failure of the keylime commands. (Encountered this in repo https://github.com/keylime/ansible-keylime-tpm-emulator)

**Comment by lukehinds** [comment]
did you want to fix this @RUKip ?

**Comment by RUKip** [comment]
Sure can try

**Comment by RUKip** [comment]
Should be added now

**Comment by mpeters** [comment]
Thanks @RUKip! Both of these fixes have been merge.
