### ISSUE TITLE
Remove rust agent

### ISSUE THREAD

**Issue by lukehinds** [keylime/ansible-keylime#5]
As this is the keylime version that seeks to use a hardware TPM, we should not be installing the rust agent at all. 

Let's remove the following

https://github.com/keylime/ansible-keylime/search?q=rust&unscoped_q=rust

**Comment by amylily1011** [comment]
Hi @lukehinds,

As this issue is labelled as 'good first issue'. I'd like to give this one a go!

**Comment by lukehinds** [comment]
Hi @amylily1011 

Great, would welcome your contribution. Let me know if you need any help at all or guidance on what needs doing.

There are some contribution guidelines here: https://github.com/keylime/keylime/blob/master/CONTRIBUTORS.md - but for a first contribution its ok if you don't make a perfect commit :)

**Comment by amylily1011** [comment]
Thanks, I was a bit trigger happy and did the commit before I got to read your message.
Would love to commit into the mainline project down the road!

PR in https://github.com/keylime/ansible-keylime/pull/6

**Comment by lukehinds** [comment]
I made a review recommendation @amylily1011 , don't worry about the commit message, we can fix that up. 

> Would love to commit into the mainline project down the road!

Would be great to have you involved! I will try to see what good first issues there are. In the meantime just running keylime and feeding back any findings you might have around usability or bugs you discover!

**Comment by lukehinds** [comment]
coincidently I just looked at your website amy and saw you have a lot of experience with UI front end experience. Keylimes UI is very basic and would highly benefit from work there if you're interested.

We are currently porting the whole project to Python 3, but not a great deal will change in the web app side. Its all centered in this file:

https://github.com/keylime/keylime/blob/master/keylime/tenant_webapp.py

**Comment by amylily1011** [comment]
@lukehinds 

That would be awesome! I'll take a look at the UI project and see where I can help. I'm trying to contribute to more opensource projects and this is a very good start. Thank you so much for helping me out with my first commit :)

**Comment by lukehinds** [comment]
that would be great thanks and thank you for your contribution!

The actual requests framework is being ported to Python 3 right now, so that will change a bit..but not the css etc.

Over time we might want to revisit how the whole web app is put together. We are using python tornado, but we don't really need an app like this (it's more for the server side where we want non blocking I/O that tornado provides), so we could always swap this out for something like flask, bottle or django etc where there are lots of decent modules we can harness for authentication etc and easier connect points with some sort of frontend js framework.

As you will see the web app / UI is quite rudimentary and very simple at the moment and more of a prototype. Would be great if we could one day have something which looks nicer and has some more enterprise features such as multi tenancy (different roles with different access levels) and nice authentication methods - that would be a long term goal to achieve though!

p.s. will close this issue, but we can still keep the discussion going in here.
